version: '3.8'

services:
  patkid-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${NODE_ENV}
        PORT: 8001
    environment:
      - TZ=Asia/Seoul # 컨테이너 내부 시간대를 KST로 설정
    image: patkid-api
    ports:
      - '8001:8001'
    volumes:
      - ./apps/api/logs:/app/apps/api/logs
      - ./public:/app/public
    networks:
      - app
    restart: always

networks:
  app:
    external: true
    name: app
