version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: place_api
    expose:
      - '3001'
    networks:
      - patkid-bridge
    logging:
      driver: awslogs
      options:
        awslogs-group: '${NODE_ENV}-place-backend'
        awslogs-region: 'ap-northeast-2'
        awslogs-stream: 'backend'
networks:
  patkid-bridge:
    external: true
