version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: maestro_api
    expose:
      - '3001'
    networks:
      - patkid-bridge
networks:
  patkid-bridge:
    external: true
